import jsPDF from 'jspdf';

export function makeSafeFilename(name: string) {
  return name
    .toLowerCase()
    .replace(/\.[a-z0-9]+$/i, '')
    .replace(/[^a-z0-9]+/gi, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 90) || 'calcsty-export';
}

function stringifyCell(value: unknown) {
  if (value === null || value === undefined) return '';
  if (Array.isArray(value) || typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function reportProfileHtml(data: unknown) {
  const profile = data && typeof data === 'object' && 'userProfile' in data ? (data as Record<string, any>).userProfile : null;
  if (!profile || typeof profile !== 'object') return '';
  const rows = [
    ['Name', profile.name],
    ['Email / ID', profile.email],
    ['Course / class', profile.course],
    ['Report purpose', profile.purpose]
  ].filter(([, value]) => value);
  if (!rows.length) return '';
  return `<section class="profile"><h2>Submitted details</h2>${rows.map(([label, value]) => `<p><strong>${escapeXml(String(label))}:</strong> ${escapeXml(String(value))}</p>`).join('')}</section>`;
}

function reportProfileText(data: unknown) {
  const profile = data && typeof data === 'object' && 'userProfile' in data ? (data as Record<string, any>).userProfile : null;
  if (!profile || typeof profile !== 'object') return [] as string[];
  return [
    profile.name ? `Name: ${profile.name}` : '',
    profile.email ? `Email / ID: ${profile.email}` : '',
    profile.course ? `Course / class: ${profile.course}` : '',
    profile.purpose ? `Report purpose: ${profile.purpose}` : ''
  ].filter(Boolean);
}

export function downloadBlob(filename: string, content: BlobPart, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export function exportJSON(filename: string, data: unknown) {
  downloadBlob(filename, JSON.stringify(data, null, 2), 'application/json');
}

export function exportCSV(filename: string, rows: Record<string, unknown>[]) {
  if (!rows.length) return downloadBlob(filename, '', 'text/csv');
  const columns = Object.keys(rows[0]);
  const csv = [
    columns.join(','),
    ...rows.map((row) => columns.map((col) => JSON.stringify(row[col] ?? '')).join(','))
  ].join('\n');
  downloadBlob(filename, csv, 'text/csv');
}

export function exportResultCSV(filename: string, data: Record<string, unknown>) {
  const rows = Object.entries(data).map(([metric, value]) => ({
    metric,
    value: stringifyCell(value)
  }));
  exportCSV(filename, rows);
}

export function exportHTML(filename: string, title: string, data: unknown) {
  const html = `<!doctype html><html><head><title>${escapeXml(title)}</title><style>body{font-family:Inter,Arial,sans-serif;padding:32px;line-height:1.55;background:#f0fdfa;color:#0f2f35}main{max-width:960px;margin:auto;background:#fff;border:1px solid #99f6e4;border-radius:24px;padding:28px;box-shadow:0 20px 60px rgba(15,118,110,.12)}pre{background:#ecfeff;padding:16px;border-radius:12px;overflow:auto;border:1px solid #ccfbf1}h1{color:#0f766e}.meta{color:#3f666b}.profile{background:#f0fdfa;border:1px solid #ccfbf1;border-radius:18px;padding:16px;margin:18px 0}.profile h2{margin-top:0;color:#0f766e}.profile p{margin:.25rem 0}</style></head><body><main><h1>${escapeXml(title)}</h1><p class="meta">Generated by Calcsty Data Garage</p>${reportProfileHtml(data)}<pre>${escapeXml(JSON.stringify(data, null, 2))}</pre></main></body></html>`;
  downloadBlob(filename, html, 'text/html');
}

export function exportPDF(filename: string, title: string, data: unknown) {
  const pdf = new jsPDF();
  pdf.setFontSize(18);
  pdf.text(title, 14, 18);
  pdf.setFontSize(10);
  pdf.text('Generated by Calcsty Data Garage', 14, 26);
  const profileLines = reportProfileText(data);
  let y = 34;
  if (profileLines.length) {
    pdf.setFontSize(12);
    pdf.text('Submitted details', 14, y);
    y += 7;
    pdf.setFontSize(10);
    profileLines.forEach((line) => {
      pdf.text(line, 14, y);
      y += 6;
    });
    y += 4;
  }
  const lines = pdf.splitTextToSize(JSON.stringify(data, null, 2), 180);
  pdf.text(lines, 14, y);
  pdf.save(filename);
}

function fallbackSvg(title: string, subtitle = 'No SVG chart was available, so this export contains a chart summary.') {
  const safeTitle = escapeXml(title);
  const safeSubtitle = escapeXml(subtitle);
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="650" viewBox="0 0 1100 650"><rect width="1100" height="650" rx="28" fill="#f8fafc"/><rect x="32" y="32" width="1036" height="586" rx="24" fill="#ffffff" stroke="#bae6fd" stroke-width="2"/><text x="72" y="112" fill="#075985" font-family="Inter,Arial,sans-serif" font-size="42" font-weight="700">${safeTitle}</text><text x="72" y="162" fill="#64748b" font-family="Inter,Arial,sans-serif" font-size="22">${safeSubtitle}</text><rect x="72" y="230" width="880" height="260" rx="18" fill="#e0f2fe"/><path d="M120 430 L260 330 L410 380 L560 260 L710 310 L870 220" fill="none" stroke="#38bdf8" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"/><circle cx="260" cy="330" r="16" fill="#818cf8"/><circle cx="410" cy="380" r="16" fill="#818cf8"/><circle cx="560" cy="260" r="16" fill="#818cf8"/><circle cx="710" cy="310" r="16" fill="#818cf8"/><text x="72" y="560" fill="#075985" font-family="Inter,Arial,sans-serif" font-size="18">Calcsty Data Garage export</text></svg>`;
}

export function getChartSvgMarkup(container: HTMLElement | null, title: string, subtitle?: string) {
  const svg = container?.querySelector('svg');
  if (!svg) return fallbackSvg(title, subtitle);

  const clone = svg.cloneNode(true) as SVGSVGElement;
  const rect = svg.getBoundingClientRect();
  const width = Math.max(900, Math.round(rect.width || 900));
  const height = Math.max(500, Math.round(rect.height || 500));
  const computed = getComputedStyle(svg);
  const color = computed.color || '#1e293b';
  const chartVars = [
    '--chart-bg',
    '--chart-text',
    '--chart-muted',
    '--chart-grid',
    '--chart-border',
    '--chart-tooltip-bg',
    '--chart-primary',
    '--chart-primary-soft',
    '--chart-secondary',
    '--chart-accent',
    '--chart-accent-soft',
    '--chart-median'
  ];
  const variableStyle = chartVars
    .map((name) => `${name}:${computed.getPropertyValue(name).trim() || '#ffffff'}`)
    .join(';');
  const chartBackground = computed.getPropertyValue('--chart-bg').trim() || '#ffffff';

  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  clone.setAttribute('width', String(width));
  clone.setAttribute('height', String(height));
  clone.setAttribute('color', color);
  clone.setAttribute('style', `${variableStyle};background:${chartBackground};color:${color}`);

  return new XMLSerializer().serializeToString(clone);
}

export function exportChartSVG(filename: string, container: HTMLElement | null, title: string, subtitle?: string) {
  const svg = getChartSvgMarkup(container, title, subtitle);
  downloadBlob(filename, svg, 'image/svg+xml;charset=utf-8');
}

export async function exportChartPNG(filename: string, container: HTMLElement | null, title: string, subtitle?: string) {
  const svg = getChartSvgMarkup(container, title, subtitle);
  const svgBlob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  await new Promise<void>((resolve, reject) => {
    const image = new Image();
    image.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = Math.max(1100, image.width || 1100);
      canvas.height = Math.max(650, image.height || 650);
      const context = canvas.getContext('2d');
      if (!context) {
        URL.revokeObjectURL(url);
        reject(new Error('Canvas export is not supported in this browser.'));
        return;
      }
      context.fillStyle = '#ffffff';
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.drawImage(image, 0, 0, canvas.width, canvas.height);
      canvas.toBlob((blob) => {
        URL.revokeObjectURL(url);
        if (!blob) {
          reject(new Error('PNG export failed.'));
          return;
        }
        downloadBlob(filename, blob, 'image/png');
        resolve();
      }, 'image/png');
    };
    image.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Unable to render chart image.'));
    };
    image.src = url;
  });
}

export async function exportChartJPG(filename: string, container: HTMLElement | null, title: string, subtitle?: string) {
  const svg = getChartSvgMarkup(container, title, subtitle);
  const svgBlob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  await new Promise<void>((resolve, reject) => {
    const image = new Image();
    image.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = Math.max(1100, image.width || 1100);
      canvas.height = Math.max(650, image.height || 650);
      const context = canvas.getContext('2d');
      if (!context) {
        URL.revokeObjectURL(url);
        reject(new Error('Canvas export is not supported in this browser.'));
        return;
      }
      context.fillStyle = '#ffffff';
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.drawImage(image, 0, 0, canvas.width, canvas.height);
      canvas.toBlob((blob) => {
        URL.revokeObjectURL(url);
        if (!blob) {
          reject(new Error('JPG export failed.'));
          return;
        }
        downloadBlob(filename, blob, 'image/jpeg');
        resolve();
      }, 'image/jpeg', 0.95);
    };
    image.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Unable to render chart image.'));
    };
    image.src = url;
  });
}

export async function exportCompletedAnalysis(options: {
  baseName: string;
  title: string;
  data: Record<string, unknown>;
  chartContainer?: HTMLElement | null;
  chartSubtitle?: string;
}) {
  const safeBase = makeSafeFilename(options.baseName);
  exportJSON(`${safeBase}-result.json`, options.data);
  exportResultCSV(`${safeBase}-result.csv`, options.data);
  exportHTML(`${safeBase}-report.html`, options.title, options.data);
  exportPDF(`${safeBase}-report.pdf`, options.title, options.data);
  exportChartSVG(`${safeBase}-chart.svg`, options.chartContainer ?? null, options.title, options.chartSubtitle);
  await exportChartPNG(`${safeBase}-chart.png`, options.chartContainer ?? null, options.title, options.chartSubtitle);
  await exportChartJPG(`${safeBase}-chart.jpg`, options.chartContainer ?? null, options.title, options.chartSubtitle);
}


export function exportSectionBundle(options: {
  baseName: string;
  title: string;
  data: Record<string, unknown>;
  csvRows?: Record<string, unknown>[];
}) {
  const safeBase = makeSafeFilename(options.baseName);
  exportJSON(`${safeBase}.json`, options.data);
  exportCSV(`${safeBase}.csv`, options.csvRows ?? Object.entries(options.data).map(([metric, value]) => ({ metric, value: stringifyCell(value) })));
  exportHTML(`${safeBase}.html`, options.title, options.data);
  exportPDF(`${safeBase}.pdf`, options.title, options.data);
}
